<template>
    <TableComponent :table="table" titleList="home">
        <template #customContent>
            <button class="bg-blue-500 text-white  rounded">Tải xuống Excel</button>
        </template>
        <template #actions="{ row }">
            <button class="btn btn-icon" @click="customAction(row)">Custom</button>
            <button class="btn btn-icon" @click="customAction(row)">Custom</button>
            <button class="btn btn-icon" @click="customAction(row)">Custom</button>
        </template>
    </TableComponent>
</template>

<script lang="ts" setup>
import { ref } from 'vue';
import TableComponent from '@/components/Table.vue';

const table = ref({
    cols: [
        { title: 'CheckStockCode', field: 'checkStockCode', show: true, sort: true },
        { title: 'Explain Note', field: 'explainNote', show: true, sort: true },
        { title: 'Request User', field: 'requestUserName', show: true, sort: true },
        { title: 'Request Date', field: 'requestDate', type: 'date', show: true, sort: true },
        { title: 'CheckStockCode', field: 'checkStockCode', show: true, sort: true },
        { title: 'Explain Note', field: 'explainNote', show: true, sort: true },
        { title: 'Request User', field: 'requestUserName', show: true, sort: true },
        { title: 'Request Date', field: 'requestDate', type: 'date', show: true, sort: true },
    ],
    data: [
        {
            checkStockCode: 'STK123',
            explainNote: 'Stock updated',
            requestUserName: 'John Doe',
            requestDate: '2024-01-01',
        },
        {
            checkStockCode: 'STK456',
            explainNote: 'Stock removed',
            requestUserName: 'Jane Smith',
            requestDate: '2024-01-05',
        },
        {
            checkStockCode: 'STK123',
            explainNote: 'Stock updated',
            requestUserName: 'John Doe',
            requestDate: '2024-01-01',
        },
        {
            checkStockCode: 'STK456',
            explainNote: 'Stock removed',
            requestUserName: 'Jane Smith',
            requestDate: '2024-01-05',
        },
        {
            checkStockCode: 'STK123',
            explainNote: 'Stock updated',
            requestUserName: 'John Doe',
            requestDate: '2024-01-01',
        },
        {
            checkStockCode: 'STK456',
            explainNote: 'Stock removed',
            requestUserName: 'Jane Smith',
            requestDate: '2024-01-05',
        },
        {
            checkStockCode: 'STK123',
            explainNote: 'Stock updated',
            requestUserName: 'John Doe',
            requestDate: '2024-01-01',
        },
        {
            checkStockCode: 'STK456',
            explainNote: 'Stock removed',
            requestUserName: 'Jane Smith',
            requestDate: '2024-01-05',
        },
        {
            checkStockCode: 'STK123',
            explainNote: 'Stock updated',
            requestUserName: 'John Doe',
            requestDate: '2024-01-01',
        },
        {
            checkStockCode: 'STK456',
            explainNote: 'Stock removed',
            requestUserName: 'Jane Smith',
            requestDate: '2024-01-05',
        },
        {
            checkStockCode: 'STK123',
            explainNote: 'Stock updated',
            requestUserName: 'John Doe',
            requestDate: '2024-01-01',
        },
        {
            checkStockCode: 'STK456',
            explainNote: 'Stock removed',
            requestUserName: 'Jane Smith',
            requestDate: '2024-01-05',
        },
        {
            checkStockCode: 'STK123',
            explainNote: 'Stock updated',
            requestUserName: 'John Doe',
            requestDate: '2024-01-01',
        },
        {
            checkStockCode: 'STK456',
            explainNote: 'Stock removed',
            requestUserName: 'Jane Smith',
            requestDate: '2024-01-05',
        },
        {
            checkStockCode: 'STK123',
            explainNote: 'Stock updated',
            requestUserName: 'John Doe',
            requestDate: '2024-01-01',
        },
        {
            checkStockCode: 'STK456',
            explainNote: 'Stock removed',
            requestUserName: 'Jane Smith',
            requestDate: '2024-01-05',
        },
        {
            checkStockCode: 'STK123',
            explainNote: 'Stock updated',
            requestUserName: 'John Doe',
            requestDate: '2024-01-01',
        },
        {
            checkStockCode: 'STK456',
            explainNote: 'Stock removed',
            requestUserName: 'Jane Smith',
            requestDate: '2024-01-05',
        },
        {
            checkStockCode: 'STK123',
            explainNote: 'Stock updated',
            requestUserName: 'John Doe',
            requestDate: '2024-01-01',
        },
        {
            checkStockCode: 'STK456',
            explainNote: 'Stock removed',
            requestUserName: 'Jane Smith',
            requestDate: '2024-01-05',
        },
        {
            checkStockCode: 'STK456',
            explainNote: 'Stock removed',
            requestUserName: 'Jane Smith',
            requestDate: '2024-01-05',
        },
        {
            checkStockCode: 'STK123',
            explainNote: 'Stock updated',
            requestUserName: 'John Doe',
            requestDate: '2024-01-01',
        },
        {
            checkStockCode: 'STK456',
            explainNote: 'Stock removed',
            requestUserName: 'Jane Smith',
            requestDate: '2024-01-05',
        },
        {
            checkStockCode: 'STK123',
            explainNote: 'Stock updated',
            requestUserName: 'John Doe',
            requestDate: '2024-01-01',
        },
        {
            checkStockCode: 'STK456',
            explainNote: 'Stock removed',
            requestUserName: 'Jane Smith',
            requestDate: '2024-01-05',
        },
        {
            checkStockCode: 'STK123',
            explainNote: 'Stock updated',
            requestUserName: 'John Doe',
            requestDate: '2024-01-01',
        },
        {
            checkStockCode: 'STK456',
            explainNote: 'Stock removed',
            requestUserName: 'Jane Smith',
            requestDate: '2024-01-05',
        },
        {
            checkStockCode: 'STK123',
            explainNote: 'Stock updated',
            requestUserName: 'John Doe',
            requestDate: '2024-01-01',
        },
        {
            checkStockCode: 'STK456',
            explainNote: 'Stock removed',
            requestUserName: 'Jane Smith',
            requestDate: '2024-01-05',
        },
        {
            checkStockCode: 'STK456',
            explainNote: 'Stock removed',
            requestUserName: 'Jane Smith',
            requestDate: '2024-01-05',
        },
        {
            checkStockCode: 'STK456',
            explainNote: 'Stock removed',
            requestUserName: 'Jane Smith',
            requestDate: '2024-01-05',
        },
        {
            checkStockCode: 'STK123',
            explainNote: 'Stock updated',
            requestUserName: 'John Doe',
            requestDate: '2024-01-01',
        },
        {
            checkStockCode: 'STK456',
            explainNote: 'Stock removed',
            requestUserName: 'Jane Smith',
            requestDate: '2024-01-05',
        },
        {
            checkStockCode: 'STK123',
            explainNote: 'Stock updated',
            requestUserName: 'John Doe',
            requestDate: '2024-01-01',
        },
        {
            checkStockCode: 'STK456',
            explainNote: 'Stock removed',
            requestUserName: 'Jane Smith',
            requestDate: '2024-01-05',
        },
        {
            checkStockCode: 'STK123',
            explainNote: 'Stock updated',
            requestUserName: 'John Doe',
            requestDate: '2024-01-01',
        },
        {
            checkStockCode: 'STK456',
            explainNote: 'Stock removed',
            requestUserName: 'Jane Smith',
            requestDate: '2024-01-05',
        },
        {
            checkStockCode: 'STK123',
            explainNote: 'Stock updated',
            requestUserName: 'John Doe',
            requestDate: '2024-01-01',
        },
        {
            checkStockCode: 'STK456',
            explainNote: 'Stock removed',
            requestUserName: 'Jane Smith',
            requestDate: '2024-01-05',
        },
        {
            checkStockCode: 'STK456',
            explainNote: 'Stock removed',
            requestUserName: 'Jane Smith',
            requestDate: '2024-01-05',
        },
        {
            checkStockCode: 'STK456',
            explainNote: 'Stock removed',
            requestUserName: 'Jane Smith',
            requestDate: '2024-01-05',
        },
        {
            checkStockCode: 'STK123',
            explainNote: 'Stock updated',
            requestUserName: 'John Doe',
            requestDate: '2024-01-01',
        },
        {
            checkStockCode: 'STK456',
            explainNote: 'Stock removed',
            requestUserName: 'Jane Smith',
            requestDate: '2024-01-05',
        },
        {
            checkStockCode: 'STK123',
            explainNote: 'Stock updated',
            requestUserName: 'John Doe',
            requestDate: '2024-01-01',
        },
        {
            checkStockCode: 'STK456',
            explainNote: 'Stock removed',
            requestUserName: 'Jane Smith',
            requestDate: '2024-01-05',
        },
        {
            checkStockCode: 'STK123',
            explainNote: 'Stock updated',
            requestUserName: 'John Doe',
            requestDate: '2024-01-01',
        },
        {
            checkStockCode: 'STK456',
            explainNote: 'Stock removed',
            requestUserName: 'Jane Smith',
            requestDate: '2024-01-05',
        },
        {
            checkStockCode: 'STK123',
            explainNote: 'Stock updated',
            requestUserName: 'John Doe',
            requestDate: '2024-01-01',
        },
        {
            checkStockCode: 'STK456',
            explainNote: 'Stock removed',
            requestUserName: 'Jane Smith',
            requestDate: '2024-01-05',
        },
        {
            checkStockCode: 'STK456',
            explainNote: 'Stock removed',
            requestUserName: 'Jane Smith',
            requestDate: '2024-01-05',
        },
        {
            checkStockCode: 'STK456',
            explainNote: 'Stock removed',
            requestUserName: 'Jane Smith',
            requestDate: '2024-01-05',
        },
        {
            checkStockCode: 'STK123',
            explainNote: 'Stock updated',
            requestUserName: 'John Doe',
            requestDate: '2024-01-01',
        },
        {
            checkStockCode: 'STK456',
            explainNote: 'Stock removed',
            requestUserName: 'Jane Smith',
            requestDate: '2024-01-05',
        },
        {
            checkStockCode: 'STK123',
            explainNote: 'Stock updated',
            requestUserName: 'John Doe',
            requestDate: '2024-01-01',
        },
        {
            checkStockCode: 'STK456',
            explainNote: 'Stock removed',
            requestUserName: 'Jane Smith',
            requestDate: '2024-01-05',
        },
        {
            checkStockCode: 'STK123',
            explainNote: 'Stock updated',
            requestUserName: 'John Doe',
            requestDate: '2024-01-01',
        },
        {
            checkStockCode: 'STK456',
            explainNote: 'Stock removed',
            requestUserName: 'Jane Smith',
            requestDate: '2024-01-05',
        },
        {
            checkStockCode: 'STK123',
            explainNote: 'Stock updated',
            requestUserName: 'John Doe',
            requestDate: '2024-01-01',
        },
        {
            checkStockCode: 'STK456',
            explainNote: 'Stock removed',
            requestUserName: 'Jane Smith',
            requestDate: '2024-01-05',
        },
        {
            checkStockCode: 'STK456',
            explainNote: 'Stock removed',
            requestUserName: 'Jane Smith',
            requestDate: '2024-01-05',
        },
        {
            checkStockCode: 'STK456',
            explainNote: 'Stock removed',
            requestUserName: 'Jane Smith',
            requestDate: '2024-01-05',
        },
        {
            checkStockCode: 'STK123',
            explainNote: 'Stock updated',
            requestUserName: 'John Doe',
            requestDate: '2024-01-01',
        },
        {
            checkStockCode: 'STK456',
            explainNote: 'Stock removed',
            requestUserName: 'Jane Smith',
            requestDate: '2024-01-05',
        },
        {
            checkStockCode: 'STK123',
            explainNote: 'Stock updated',
            requestUserName: 'John Doe',
            requestDate: '2024-01-01',
        },
        {
            checkStockCode: 'STK456',
            explainNote: 'Stock removed',
            requestUserName: 'Jane Smith',
            requestDate: '2024-01-05',
        },
        {
            checkStockCode: 'STK123',
            explainNote: 'Stock updated',
            requestUserName: 'John Doe',
            requestDate: '2024-01-01',
        },
        {
            checkStockCode: 'STK456',
            explainNote: 'Stock removed',
            requestUserName: 'Jane Smith',
            requestDate: '2024-01-05',
        },
        {
            checkStockCode: 'STK123',
            explainNote: 'Stock updated',
            requestUserName: 'John Doe',
            requestDate: '2024-01-01',
        },
        {
            checkStockCode: 'STK456',
            explainNote: 'Stock removed',
            requestUserName: 'Jane Smith',
            requestDate: '2024-01-05',
        },
        {
            checkStockCode: 'STK456',
            explainNote: 'Stock removed',
            requestUserName: 'Jane Smith',
            requestDate: '2024-01-05',
        },
        {
            checkStockCode: 'STK456',
            explainNote: 'Stock removed',
            requestUserName: 'Jane Smith',
            requestDate: '2024-01-05',
        },
        {
            checkStockCode: 'STK123',
            explainNote: 'Stock updated',
            requestUserName: 'John Doe',
            requestDate: '2024-01-01',
        },
        {
            checkStockCode: 'STK456',
            explainNote: 'Stock removed',
            requestUserName: 'Jane Smith',
            requestDate: '2024-01-05',
        },
        {
            checkStockCode: 'STK123',
            explainNote: 'Stock updated',
            requestUserName: 'John Doe',
            requestDate: '2024-01-01',
        },
        {
            checkStockCode: 'STK456',
            explainNote: 'Stock removed',
            requestUserName: 'Jane Smith',
            requestDate: '2024-01-05',
        },
        {
            checkStockCode: 'STK123',
            explainNote: 'Stock updated',
            requestUserName: 'John Doe',
            requestDate: '2024-01-01',
        },
        {
            checkStockCode: 'STK456',
            explainNote: 'Stock removed',
            requestUserName: 'Jane Smith',
            requestDate: '2024-01-05',
        },
        {
            checkStockCode: 'STK123',
            explainNote: 'Stock updated',
            requestUserName: 'John Doe',
            requestDate: '2024-01-01',
        },
        {
            checkStockCode: 'STK456',
            explainNote: 'Stock removed',
            requestUserName: 'Jane Smith',
            requestDate: '2024-01-05',
        },
        {
            checkStockCode: 'STK456',
            explainNote: 'Stock removed',
            requestUserName: 'Jane Smith',
            requestDate: '2024-01-05',
        },
        {
            checkStockCode: 'STK456',
            explainNote: 'Stock removed',
            requestUserName: 'Jane Smith',
            requestDate: '2024-01-05',
        },
        {
            checkStockCode: 'STK123',
            explainNote: 'Stock updated',
            requestUserName: 'John Doe',
            requestDate: '2024-01-01',
        },
        {
            checkStockCode: 'STK456',
            explainNote: 'Stock removed',
            requestUserName: 'Jane Smith',
            requestDate: '2024-01-05',
        },
        {
            checkStockCode: 'STK123',
            explainNote: 'Stock updated',
            requestUserName: 'John Doe',
            requestDate: '2024-01-01',
        },
        {
            checkStockCode: 'STK456',
            explainNote: 'Stock removed',
            requestUserName: 'Jane Smith',
            requestDate: '2024-01-05',
        },
        {
            checkStockCode: 'STK123',
            explainNote: 'Stock updated',
            requestUserName: 'John Doe',
            requestDate: '2024-01-01',
        },
        {
            checkStockCode: 'STK456',
            explainNote: 'Stock removed',
            requestUserName: 'Jane Smith',
            requestDate: '2024-01-05',
        },
        {
            checkStockCode: 'STK123',
            explainNote: 'Stock updated',
            requestUserName: 'John Doe',
            requestDate: '2024-01-01',
        },
        {
            checkStockCode: 'STK456',
            explainNote: 'Stock removed',
            requestUserName: 'Jane Smith',
            requestDate: '2024-01-05',
        },
        {
            checkStockCode: 'STK456',
            explainNote: 'Stock removed',
            requestUserName: 'Jane Smith',
            requestDate: '2024-01-05',
        },
        {
            checkStockCode: 'STK456',
            explainNote: 'Stock removed',
            requestUserName: 'Jane Smith',
            requestDate: '2024-01-05',
        },
        {
            checkStockCode: 'STK123',
            explainNote: 'Stock updated',
            requestUserName: 'John Doe',
            requestDate: '2024-01-01',
        },
        {
            checkStockCode: 'STK456',
            explainNote: 'Stock removed',
            requestUserName: 'Jane Smith',
            requestDate: '2024-01-05',
        },
        {
            checkStockCode: 'STK123',
            explainNote: 'Stock updated',
            requestUserName: 'John Doe',
            requestDate: '2024-01-01',
        },
        {
            checkStockCode: 'STK456',
            explainNote: 'Stock removed',
            requestUserName: 'Jane Smith',
            requestDate: '2024-01-05',
        },
        {
            checkStockCode: 'STK123',
            explainNote: 'Stock updated',
            requestUserName: 'John Doe',
            requestDate: '2024-01-01',
        },
        {
            checkStockCode: 'STK456',
            explainNote: 'Stock removed',
            requestUserName: 'Jane Smith',
            requestDate: '2024-01-05',
        },
        {
            checkStockCode: 'STK123',
            explainNote: 'Stock updated',
            requestUserName: 'John Doe',
            requestDate: '2024-01-01',
        },
        {
            checkStockCode: 'STK456',
            explainNote: 'Stock removed',
            requestUserName: 'Jane Smith',
            requestDate: '2024-01-05',
        },
        {
            checkStockCode: 'STK456',
            explainNote: 'Stock removed',
            requestUserName: 'Jane Smith',
            requestDate: '2024-01-05',
        },
        {
            checkStockCode: 'STK456',
            explainNote: 'Stock removed',
            requestUserName: 'Jane Smith',
            requestDate: '2024-01-05',
        },
        {
            checkStockCode: 'STK123',
            explainNote: 'Stock updated',
            requestUserName: 'John Doe',
            requestDate: '2024-01-01',
        },
        {
            checkStockCode: 'STK456',
            explainNote: 'Stock removed',
            requestUserName: 'Jane Smith',
            requestDate: '2024-01-05',
        },
        {
            checkStockCode: 'STK123',
            explainNote: 'Stock updated',
            requestUserName: 'John Doe',
            requestDate: '2024-01-01',
        },
        {
            checkStockCode: 'STK456',
            explainNote: 'Stock removed',
            requestUserName: 'Jane Smith',
            requestDate: '2024-01-05',
        },
        {
            checkStockCode: 'STK123',
            explainNote: 'Stock updated',
            requestUserName: 'John Doe',
            requestDate: '2024-01-01',
        },
        {
            checkStockCode: 'STK456',
            explainNote: 'Stock removed',
            requestUserName: 'Jane Smith',
            requestDate: '2024-01-05',
        },
        {
            checkStockCode: 'STK123',
            explainNote: 'Stock updated',
            requestUserName: 'John Doe',
            requestDate: '2024-01-01',
        },
        {
            checkStockCode: 'STK456',
            explainNote: 'Stock removed',
            requestUserName: 'Jane Smith',
            requestDate: '2024-01-05',
        },
        {
            checkStockCode: 'STK456',
            explainNote: 'Stock removed',
            requestUserName: 'Jane Smith',
            requestDate: '2024-01-05',
        },
        {
            checkStockCode: 'STK456',
            explainNote: 'Stock removed',
            requestUserName: 'Jane Smith',
            requestDate: '2024-01-05',
        },
        {
            checkStockCode: 'STK123',
            explainNote: 'Stock updated',
            requestUserName: 'John Doe',
            requestDate: '2024-01-01',
        },
        {
            checkStockCode: 'STK456',
            explainNote: 'Stock removed',
            requestUserName: 'Jane Smith',
            requestDate: '2024-01-05',
        },
        {
            checkStockCode: 'STK123',
            explainNote: 'Stock updated',
            requestUserName: 'John Doe',
            requestDate: '2024-01-01',
        },
        {
            checkStockCode: 'STK456',
            explainNote: 'Stock removed',
            requestUserName: 'Jane Smith',
            requestDate: '2024-01-05',
        },
        {
            checkStockCode: 'STK123',
            explainNote: 'Stock updated',
            requestUserName: 'John Doe',
            requestDate: '2024-01-01',
        },
        {
            checkStockCode: 'STK456',
            explainNote: 'Stock removed',
            requestUserName: 'Jane Smith',
            requestDate: '2024-01-05',
        },
        {
            checkStockCode: 'STK123',
            explainNote: 'Stock updated',
            requestUserName: 'John Doe',
            requestDate: '2024-01-01',
        },
        {
            checkStockCode: 'STK456',
            explainNote: 'Stock removed',
            requestUserName: 'Jane Smith',
            requestDate: '2024-01-05',
        },
        {
            checkStockCode: 'STK456',
            explainNote: 'Stock removed',
            requestUserName: 'Jane Smith',
            requestDate: '2024-01-05',
        },
        {
            checkStockCode: 'STK456',
            explainNote: 'Stock removed',
            requestUserName: 'Jane Smith',
            requestDate: '2024-01-05',
        },
        {
            checkStockCode: 'STK123',
            explainNote: 'Stock updated',
            requestUserName: 'John Doe',
            requestDate: '2024-01-01',
        },
        {
            checkStockCode: 'STK456',
            explainNote: 'Stock removed',
            requestUserName: 'Jane Smith',
            requestDate: '2024-01-05',
        },
        {
            checkStockCode: 'STK123',
            explainNote: 'Stock updated',
            requestUserName: 'John Doe',
            requestDate: '2024-01-01',
        },
        {
            checkStockCode: 'STK456',
            explainNote: 'Stock removed',
            requestUserName: 'Jane Smith',
            requestDate: '2024-01-05',
        },
        {
            checkStockCode: 'STK123',
            explainNote: 'Stock updated',
            requestUserName: 'John Doe',
            requestDate: '2024-01-01',
        },
        {
            checkStockCode: 'STK456',
            explainNote: 'Stock removed',
            requestUserName: 'Jane Smith',
            requestDate: '2024-01-05',
        },
        {
            checkStockCode: 'STK123',
            explainNote: 'Stock updated',
            requestUserName: 'John Doe',
            requestDate: '2024-01-01',
        },
        {
            checkStockCode: 'STK456',
            explainNote: 'Stock removed',
            requestUserName: 'Jane Smith',
            requestDate: '2024-01-05',
        },
        {
            checkStockCode: 'STK456',
            explainNote: 'Stock removed',
            requestUserName: 'Jane Smith',
            requestDate: '2024-01-05',
        },
        {
            checkStockCode: 'STK456',
            explainNote: 'Stock removed',
            requestUserName: 'Jane Smith',
            requestDate: '2024-01-05',
        },
        {
            checkStockCode: 'STK123',
            explainNote: 'Stock updated',
            requestUserName: 'John Doe',
            requestDate: '2024-01-01',
        },
        {
            checkStockCode: 'STK456',
            explainNote: 'Stock removed',
            requestUserName: 'Jane Smith',
            requestDate: '2024-01-05',
        },
        {
            checkStockCode: 'STK123',
            explainNote: 'Stock updated',
            requestUserName: 'John Doe',
            requestDate: '2024-01-01',
        },
        {
            checkStockCode: 'STK456',
            explainNote: 'Stock removed',
            requestUserName: 'Jane Smith',
            requestDate: '2024-01-05',
        },
        {
            checkStockCode: 'STK123',
            explainNote: 'Stock updated',
            requestUserName: 'John Doe',
            requestDate: '2024-01-01',
        },
        {
            checkStockCode: 'STK456',
            explainNote: 'Stock removed',
            requestUserName: 'Jane Smith',
            requestDate: '2024-01-05',
        },
        {
            checkStockCode: 'STK123',
            explainNote: 'Stock updated',
            requestUserName: 'John Doe',
            requestDate: '2024-01-01',
        },
        {
            checkStockCode: 'STK456',
            explainNote: 'Stock removed',
            requestUserName: 'Jane Smith',
            requestDate: '2024-01-05',
        },
    ],
});

// Hàm cho nút custom
function customAction(row: any) {
    console.log('Custom action for row:', row);
}
</script>
